FROM node:20-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Habilitar pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# En modo DEV, instalamos todo (incluyendo devDependencies)
COPY pnpm-lock.yaml package.json ./
RUN pnpm install

# Copiamos el resto de los archivos de configuración
COPY next.config.ts tsconfig.json drizzle.config.ts ./
# La carpeta /src se montará vía volúmenes en docker-compose.yml, pero copiamos para asegurar
COPY src ./src

ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV development

# Exponemos el puerto interno (que luego mapeamos al 3080)
EXPOSE 3000

CMD ["pnpm", "dev"]